#!/bin/bash
# Lab: 10
# Name: # Lab Section Number: 301
# Name of the script file is "mycalc"
# Date: 
# Purpose: Provide basic calculations


var1=$1
choice=$2
var2=$3
if [ $# != 3 ]; then
	echo -n "enter first int: "
	read  var1
	read choice
	read var2
fi


add() {
	((var3=$var1+$var2))
	echo "The sum of $var1 plus $var2 equals $var3";
	}

subtract()  {
	((var3=$var1-$var2))
	echo "The subtracted entted en of $var1 minus $var2 equals $var3";
	}

multiply() {
	((var3=$var1*$var2))
	echo "The multiply of $var1 multilpy $var2 equals $var3";
	}

#case $choice in

	
	#+) add () {
	#	((var3=$var1+$var2))
	#	echo "The sum of $var1 plus $var2 equals $var3";
	#	}
	#	;;

	#-) subtrac t ()  {
	#	((var3=$var1-$var2))
	#	echo "The subtracted entted en of $var1 minus $var2 equals $var3";
	#	}
	#	;;
	#*) multiply () {
	#	((var3=$var1*$var2))
	#	echo "The multiply of $var1 multilpy $var2 equals $var3";
	#	}
	#	;;

#esac


if [ "$choice" = "+" ]; then
	add $var1 $var2

elif [ "$choice" = "-" ]; then
	subtract $var1 $var2

elif [ "$choice" = "*" ]; then
	multiply $var1 $var2

else echo "Enter a valid choice";
fi


